# Basic set up for gradle package manager
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore: # Ignore Spock updates Groovy 4 becomes available
      - dependency-name: "org.spockframework:spock-core"
      - dependency-name: "org.spockframework:spock-spring"

